// Generated by CoffeeScript 1.8.0
(function() {
  var PushEvernote, Task, async, noteStore, txErr;

  PushEvernote = require('../lib/pushEvernote');

  async = require('async');

  Task = require('../models/task');

  txErr = require('../lib/txErr');

  noteStore = require('../lib/noteStore');

  async.waterfall([
    function(cb) {
      return Task.find({
        status: 1
      }, null, {
        sort: {
          _id: -1
        }
      }, function(err, rows) {
        if (err) {
          return txErr({
            err: err,
            fun: 'TaskFind'
          }, callback);
        }
        return cb(null, rows);
      });
    }, function(rows, cb) {
      return async.eachSeries(rows, function(item, callback) {
        var p;
        p = new PushEvernote(item.url, noteStore, item.noteBook);
        return p.pushNote(callback);
      }, function() {
        return console.log("#  all do #");
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=test_fav.js.map
