// Generated by CoffeeScript 1.8.0
(function() {
  var GetCol, j, noteStore, rule, schedule;

  GetCol = require('../lib/getCollection');

  noteStore = require('../lib/noteStore');

  schedule = require("node-schedule");

  rule = new schedule.RecurrenceRule();

  rule.dayOfWeek = [0, new schedule.Range(1, 6)];

  rule.hour = 18;

  rule.minute = 30;

  j = schedule.scheduleJob(rule, function() {
    var col;
    col = [
      {
        url: 'https://api.zhihu.com/collections/29469118/answers',
        noteBook: 'f082258a-fd9a-4713-98a0-d85fa838f019'
      }
    ];
    return col.forEach(function(item, v) {
      var t;
      t = new GetCol(noteStore, item.noteBook);
      return t.getColList(item.url);
    });
  });

}).call(this);

//# sourceMappingURL=test-getcol.js.map
