// Generated by CoffeeScript 1.8.0
(function() {
  var GetCol, col, noteStore, rule, schedule;

  GetCol = require('../lib/getCollection');

  noteStore = require('../lib/noteStore');

  schedule = require("node-schedule");

  rule = new schedule.RecurrenceRule();

  rule.dayOfWeek = [0, new schedule.Range(1, 6)];

  rule.hour = 18;

  rule.minute = 30;

  col = [
    {
      url: 'https://api.zhihu.com/collections/19932288/answers',
      noteBook: '4aad11b8-b6ac-4afc-b4c3-103a530c6dc4'
    }, {
      url: 'https://api.zhihu.com/collections/19745661/answers',
      noteBook: '371df8dd-d950-4e66-a801-2ce719cab2d3'
    }
  ];

  col.forEach(function(item, v) {
    var t;
    t = new GetCol(noteStore, item.noteBook);
    return t.getColList(item.url);
  });

}).call(this);

//# sourceMappingURL=test-getcol.js.map
