// Generated by CoffeeScript 1.10.0
(function() {
  var Check, PushEvernote, Task, UpdateEvernote, async, col, mongoose, noteStore, txErr;

  PushEvernote = require('./lib/pushEvernote');

  async = require('async');

  Task = require('./models/task');

  txErr = require('./lib/txErr');

  noteStore = require('./lib/noteStore');

  UpdateEvernote = require('./lib/updateEvernote');

  Check = require('./lib/check');

  mongoose = require('./models/mongoose');

  col = [
    {
      url: 'https://api.zhihu.com/collections/29469118/answers',
      noteBook: 'f082258a-fd9a-4713-98a0-d85fa838f019'
    }
  ];

  async.waterfall([
    function(cb) {
      return async.eachLimit(col, 4, function(item, callback) {
        var c, recursive;
        recursive = Math.random() > 0.5 ? true : false;
        c = new Check(item.url, item.noteBook, recursive);
        return c.getList(item.url, callback);
      }, function(err) {
        if (err) {
          return console.log(err);
        }
        mongoose.connection.close();
        return cb();
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=run_check.js.map
