// Generated by CoffeeScript 1.10.0
(function() {
  var Check, PushEvernote, Task, UpdateEvernote, async, mongoose, noteStore, schedule, txErr;

  PushEvernote = require('./lib/pushEvernote');

  async = require('async');

  Task = require('./models/task');

  txErr = require('./lib/txErr');

  noteStore = require('./lib/noteStore');

  UpdateEvernote = require('./lib/updateEvernote');

  Check = require('./lib/check');

  mongoose = require('./models/mongoose');

  schedule = require('node-schedule');

  schedule.scheduleJob('15,45 8-23 * * *', function() {
    return async.waterfall([
      function(cb) {
        return Task.find({
          status: 1
        }, null, {
          sort: {
            _id: -1
          }
        }, function(err, rows) {
          if (err) {
            return txErr({
              err: err,
              fun: 'TaskFind'
            }, callback);
          }
          return cb(null, rows);
        });
      }, function(rows, cb) {

        /* 创建 */
        return async.eachSeries(rows, function(item, callback) {
          var p;
          p = new PushEvernote(item.url, noteStore, item.noteBook);
          return p.pushNote(callback);
        }, function() {
          console.log("#  all do #");
          return cb();
        });
      }, function(cb) {

        /* 更新 */
        return async.waterfall([
          function(cb) {
            return Task.find({
              status: 3
            }, null, {
              sort: {
                _id: -1
              }
            }, function(err, rows) {
              if (err) {
                return txErr({
                  err: err,
                  fun: 'TaskFind'
                }, callback);
              }
              return cb(null, rows);
            });
          }, function(rows) {
            return async.eachSeries(rows, function(item, callback) {
              var u;
              if (item.guid) {
                u = new UpdateEvernote(item.url, noteStore, item.noteBook, item.guid, item);
                return u.upNote(callback);
              }
            }, function() {
              return console.log("# all do up #");
            });
          }
        ]);
      }
    ]);
  });

}).call(this);

//# sourceMappingURL=run_push.js.map
