// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, makeNote;

  Evernote = require('evernote').Evernote;

  makeNote = function(noteStore, noteTitle, tagList, noteBody, sourceUrl, resources, created, updated, notebookGuid, callback) {
    var attr, nBody, ourNote;
    nBody = '<?xml version="1.0" encoding="UTF-8"?>';
    nBody += '<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">';
    nBody += '<en-note>' + noteBody + '</en-note>';
    ourNote = new Evernote.Note;
    attr = new Evernote.NoteAttributes;
    attr.sourceURL = sourceUrl;
    ourNote.title = noteTitle;
    ourNote.content = nBody;
    ourNote.attributes = attr;
    ourNote.resources = resources;
    ourNote.tagNames = tagList;
    ourNote.created = created * 1000;
    ourNote.updated = updated * 1000;
    ourNote.notebookGuid = notebookGuid;
    return noteStore.createNote(ourNote, function(err, note) {
      if (err) {
        console.log(err);
        console.log(noteTitle);
        return callback(err);
      } else {
        return callback(null, note);
      }
    });
  };

  module.exports = makeNote;

}).call(this);

//# sourceMappingURL=createNote.js.map
