// Generated by CoffeeScript 1.8.0
(function() {
  var nodemailer;

  nodemailer = require('nodemailer');

  module.exports = function() {
    var transporter;
    transporter = nodemailer.createTransport({
      service: 'QQ',
      auth: {
        user: process.env.ERROR_EMAIL,
        pass: process.env.ERROR_EMAIL_PWD
      }
    });
    return {
      send: function(body, to, subj) {
        if (to == null) {
          to = 'youqingkui@qq.com';
        }
        if (subj == null) {
          subj = 'hi';
        }
        return transporter.sendMail({
          from: 'youqingkui@qq.com',
          to: to,
          subject: subj,
          html: body,
          generateTextFromHtml: true
        }, function(err, info) {
          if (err) {
            return console.log(err);
          }
          return console.log(info);
        });
      }
    };
  };

}).call(this);

//# sourceMappingURL=email.js.map
