// Generated by CoffeeScript 1.8.0
(function() {
  var GetCol, Task, async, fs, path, queue, requrest, txErr;

  requrest = require('request');

  fs = require('fs');

  path = require('path');

  queue = require('./getAnswers');

  async = require('async');

  txErr = require('./txErr');

  Task = require('../models/task');

  GetCol = (function() {
    function GetCol(noteStore, noteBook) {
      this.noteStore = noteStore;
      this.noteBook = noteBook;
      this.headers = {
        'User-Agent': 'osee2unifiedRelease/332 CFNetwork/711.3.18 Darwin/14.0.0',
        'Authorization': 'oauth 5774b305d2ae4469a2c9258956ea49',
        'Content-Type': 'application/json'
      };
    }

    GetCol.prototype.getColList = function(url) {
      var op, self;
      self = this;
      op = {
        url: url,
        headers: self.headers,
        gzip: true
      };
      return async.auto({
        getList: function(cb) {
          return requrest.get(op, function(err, res, body) {
            var data;
            if (err) {
              return txErr(op.url, 1, {
                err: err,
                fun: 'getList'
              });
            }
            data = JSON.parse(body);
            return cb(null, data);
          });
        },
        checkList: [
          'getList', function(cb, result) {
            var answerList, data;
            data = result.getList;
            if (data.data.length) {
              answerList = data.data;
              answerList.forEach(function(answer) {
                return Task.findOne({
                  url: answer.url
                }, function(err, row) {
                  if (err) {
                    return txErr(url, 5, {
                      err: err,
                      answer: answer.url,
                      fun: 'checkList'
                    });
                  }
                  if (row) {
                    return console.log("already exits ==>", answer.url);
                  } else {
                    return self.addTask(answer.url);
                  }
                });
              });
              return self.getColList(data.paging.next);
            } else {
              return console.log(data);
            }
          }
        ]
      });
    };

    GetCol.prototype.addTask = function(url) {
      var self;
      self = this;
      return async.auto({
        addDB: function(callback) {
          var task;
          task = new Task;
          task.url = url;
          return task.save(function(err, row) {
            if (err) {
              return txErr(url, 5, {
                err: err,
                fun: 'addDB'
              });
            }
            return callback();
          });
        },
        addDo: [
          'addDB', function(callback) {
            return queue.push({
              url: url,
              noteStore: self.noteStore,
              noteBook: self.noteBook
            }, function(err) {
              if (err) {
                return txErr(url, 6, {
                  err: err,
                  fun: 'addDo'
                });
              }
            });
          }
        ]
      });
    };

    GetCol.prototype.changeStatus = function(url, status, cb) {
      return async.auto({
        findUrl: function(callback) {
          return Task.findOne({
            url: url
          }, function(err, row) {
            if (err) {
              return cb(err, status);
            }
            if (row) {
              return callback(null, row);
            }
          });
        },
        change: [
          'findUrl', function(callback, result) {
            var row;
            row = result.findUrl;
            row.status = status;
            return row.save(function(err, row) {
              if (err) {
                return cb(err);
              }
              return cb(null, status);
            });
          }
        ]
      });
    };

    GetCol.prototype.getColInfo = function() {};

    return GetCol;

  })();

  module.exports = GetCol;

}).call(this);

//# sourceMappingURL=getCollection.js.map
