// Generated by CoffeeScript 1.10.0
(function() {
  var instapush, instapush_notify;

  instapush = require("instapush");

  instapush.settings({
    id: process.env.instapush_id,
    secret: process.env.instapush_secret
  });

  instapush_notify = function(title) {
    var date, nowDate;
    nowDate = new Date();
    date = nowDate.toLocaleDateString() + " " + nowDate.toLocaleTimeString();
    return instapush.notify({
      'event': 'zhihufav',
      'trackers': {
        'title': title,
        'date': date
      }
    }, function(err, res) {
      if (err) {
        console.log(err);
      }
      return console.log(res);
    });
  };

  module.exports = instapush_notify;

}).call(this);

//# sourceMappingURL=instapush_notify.js.map
