// Generated by CoffeeScript 1.8.0
(function() {
  var email, txErr;

  email = require('./email')();

  txErr = function(href, type, infoJson, cb) {
    var emailBody, log;
    console.log(infoJson.err);
    log = {};
    log.href = href;
    log.type = type;
    log.info = JSON.stringify(infoJson);
    emailBody = JSON.stringify(log);
    email.send(emailBody);
    if (cb) {
      return cb(infoJson.err);
    }
  };

  module.exports = txErr;

}).call(this);

//# sourceMappingURL=txErr.js.map
