// Generated by CoffeeScript 1.8.0
(function() {
  var email, txErr;

  email = require('./email')();

  txErr = function(href, type, infoJson, cb) {
    var emailBody, log;
    console.log(infoJson.err);
    log = new ErrLog();
    log.href = href;
    log.type = type;
    log.info = JSON.stringify(infoJson);
    log.save(function(err, row) {
      if (err) {
        return console.log(err);
      }
    });
    emailBody = JSON.stringify(log);
    email.send(emailBody);
    if (cb) {
      return cb(infoJson.err);
    }
  };

  module.exports = txErr;

}).call(this);

//# sourceMappingURL=txErr.js.map
