// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, updateNote;

  Evernote = require('evernote').Evernote;

  updateNote = function(noteStore, guid, noteTitle, noteBody, options, callback) {
    var attr, nBody, ourNote;
    nBody = '<?xml version="1.0" encoding="UTF-8"?>';
    nBody += '<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">';
    nBody += '<en-note>' + noteBody + '</en-note>';
    ourNote = new Evernote.Note();
    ourNote.guid = guid;
    ourNote.title = noteTitle + '【UP】';
    ourNote.content = nBody;
    attr = new Evernote.NoteAttributes;
    if (options) {
      if (options.sourceUrl) {
        attr.sourceURL = options.sourceUrl;
      }
      if (options.resources) {
        ourNote.resources = options.resources;
      }
      if (options.tagNames) {
        ourNote.tagNames = options.tagNames;
      }
      if (options.notebookGuid) {
        ourNote.notebookGuid = options.notebookGuid;
      }
      if (options.created) {
        ourNote = options.created * 1000;
      }
      if (options.updated) {
        ourNote.updated = options.updated * 1000;
      }
    }
    ourNote.attributes = attr;
    return noteStore.updateNote(ourNote, function(err, note) {
      if (err) {
        console.log(err);
        console.log(noteTitle);
        return callback(err);
      } else {
        return callback(null, note);
      }
    });
  };

  module.exports = updateNote;

}).call(this);

//# sourceMappingURL=updateNote.js.map
