// Generated by CoffeeScript 1.8.0
(function() {
  var mongoose;

  mongoose = require('mongoose');

  mongoose.connect('mongodb://localhost/zhihufav2evernote-test');

  module.exports = mongoose;

}).call(this);

//# sourceMappingURL=mongoose.js.map
